### ISSUE TITLE
"Minute" indicator increases when seconds reaches 30

### ISSUE THREAD

**Issue by josehfp** [fmilani/contatempo#18] opened 2018-03-30 15:46 UTC
In the Label that indicates current time worked, when the "seconds" indicator reaches 30, the "minutes" is increased by one.
![image](https://user-images.githubusercontent.com/15706217/38143647-db8859ee-3417-11e8-8f19-47e271ddf921.png)

**Comment by fmilani** [comment] 2018-04-08 14:48
Hey @josehfp 

First of all, thanks for reporting this issue! :smile: 

This is a regression bug caused by the update of the moment-duration-format package on current release (v0.5.1). I updated the package from version 1.3.0 to 2.2.2 (which indicates that there are non-backwards compatibility changes. I know, my bad :sweat_smile: )

Anyway, a fix for this problem that you found is coming!!!

Thanks for your patience

![bitmoji](https://render.bitstrips.com/v2/cpanel/25e6c2f3-01c4-45ef-a232-b0d33f830032-af22f863-95b0-487b-afe3-7d65e6e69a8c-v1.png?transparent=1&palette=1&width=246)

**Closed as completed** 2018-04-08 14:56 UTC
